### ISSUE TITLE
Big Open Space when Visuals are open but song doesn't have any tags

### ISSUE THREAD

**Issue by michael-tiger-2010** [RJRock12/MediaView#2]
The visuals tab (opened by alt+v) has a big void when a song doesn't have tags.

**Comment by RJRock12** [comment]
Possible solution: 
Use a detection system similar to the one used for switching between video and audio in order to hide the gap.

**Comment by RJRock12** [comment]
Note: The gap shows in video mode as well.

**Comment by RJRock12** [comment]
Developer decision to ignore the bug, as it will not affect the user experience. Open a pull request if you wish to fix it yourself.

**Comment by michael-tiger-2010** [comment]
Fixing.

**Comment by michael-tiger-2010** [comment]
Done!
