### ISSUE TITLE
[UI]

### ISSUE THREAD

**Issue by michael-tiger-2010** [RJRock12/MediaView#7]
##Problem
Alt+Space may not be the best keyboard shortcut

##Possible Solution
Change shortcut

**Comment by RJRock12** [comment]
- You're free to put in shortcut suggestions here.
- Shortcut must begin with alt. 
- Will close this issue once a replacement is found.

**Comment by RJRock12** [comment]
My personal suggestions: (will edit this comment to save space):

1. alt+w
2. alt+q

**Comment by michael-tiger-2010** [comment]
alt+q is quite good. Writing down for next version.
